install.packages("medicaldata")
install.packages("here")
install.packages("gtsummary")
install.packages("ggplot2")
library(here)
library(medicaldata)
library(gtsummary)
library(ggplot2)
data(package = "medicaldata")
here::here("data", "raw")
strep_tb_data <- medicaldata::strep_tb
file_path <-here::here("data", "raw")
saveRDS(strep_tb_data, file = "data.rds")
source_path <- here("data.rds")
destination_path <- here("data", "data.rds")
file.rename(source_path, destination_path)
